--- # directory creation
- name: my test playbook
  hosts: all
  user: ansible
  become: yes
  connection: ssh



  tasks:
    - name: copying a file
      copy:
        src: /home/ansible/index.html
        dest: /home/ansible
        owner: hari  
