--- # delete directory
- name: my test playbook
  hosts: webservers
  become: yes






  tasks: 
    - name: deleting a directory
      file:
        path: /home/ansible/haridir
        state: absent  
