--- # my handlers playbook
- hosts: webservers
  user: ansible
  become: yes
  connection: ssh



  tasks:
    - name: removing HTTPD into webservers
      action: yum name=httpd state=absent
      notify: start httpd service 
 
 
  handlers: 

    - name: start httpd service
      action: service name=httpd state=stopped    
