--- # software installation
- name: my test playbook
  hosts: webservers
  user: ansible
  connection: ssh
  become: true



  tasks:
    - name: installing  package into hosts
      yum:
        name: docker
        state: installed  
