--- 
- name: install java,download and install tomcat
  hosts: all
  user: ansible
  become: yes
  connection: ssh 


  tasks:
       - name: install java on RedHat
         yum:
           name: java
           state: installed
         when: ansible_os_family == "RedHat"
       

       - name: install java on Debian     
         apt:
           name: default-jdk
           state: present
         when: ansible_os_family == "Debian"


       - name: Download tomcat software
         get_url:
           url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.78/bin/apache-tomcat-8.5.78.tar.gz
           dest: /opt


       - name: extract tomcat softare
         unarchive:
           src: /opt/apache-tomcat-8.5.78.tar.gz
           dest: /opt
           remote_src: yes

       - name: providing executable permissions
         file:
           path: /opt/apache-tomcat-8.5.78/bin/startup.sh
           mode: 0777


       - name: start tomcat service
         shell: nohup ./startup.sh       
         args:
           chdir: /opt/apache-tomcat-8.5.78/bin  


